# Generated by Django 5.0.1 on 2024-01-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=13, null=True)),
                ('address', models.CharField(max_length=254)),
                ('dateOfAppointment', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('slot', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
