# Generated by Django 5.0.1 on 2024-02-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_message_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('msg', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
