# Generated by Django 5.0.1 on 2024-02-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='dentists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_name', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=128)),
                ('stage', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=128)),
                ('msg', models.CharField(max_length=128, null=True)),
                ('profession', models.EmailField(max_length=128, null=True)),
            ],
        ),
    ]
