# Generated by Django 5.0.1 on 2024-02-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_dentists_pricing_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='profession',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
