# Generated by Django 5.0.1 on 2024-02-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_appointments_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='email_link',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='facebook_link',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='dentist',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='dentist',
            name='instagram_link',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
